name: test
run-name: ${{ github.actor }} is running tests.
on: [push]
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        with:
          run: npm install
      - run: npx tsc --noEmit
      - run: npm test
      - name: Cypress
        uses: cypress-io/github-action@v3
        with:
          # project: ./site
          browser: chrome
          dev: npm run dev
          wait-on: "http://localhost:5173"
